name: blood_bank_task
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 900
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 500
        - asset: assets/fonts/Metropolis-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 300
