name: blood_bank_task
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # BLOC
  flutter_bloc: ^8.0.1
  # DEPENDENCY INJECTION
  get_it: ^7.2.0
  http:
  freezed_annotation: ^1.1.0

  # FUNCTIONAL PROGRAMMING
  dartz: ^0.10.1
 
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.7


flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 900
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 500
        - asset: assets/fonts/Metropolis-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 300
